import { Inter } from "next/font/google";
import "./globals.css";
import NavbarMobile from "./components/layout/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OMO! Healthy Snack | Snack Sehat untuk Anak Indonesia!",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <main>
          <NavbarMobile />
          {children}
        </main>
      </body>
    </html>
  );
}
